# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8282019dbf6a3bbab9924d25e748c5c5a40e883928d52a835a5da245e924131cd8ff07df07aa98ab47d535e11a12739dcbd3bbfd44e5971ce62fac5bb49bac2f

test:
  secret_key_base: 7d8e62bc9c250fdb303c558c17a05094ce50c3de4998458a6eddc64e8673a49a018f4c861b740a515ad5afe9d6770bf6bcdebedd236533b6eb6d88d863043932

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
